import { createHash, randomUUID } from 'node:crypto';
import { Inject, Injectable } from '@nestjs/common';
import { COMMUNICATION_PROVIDER, INCIDENT_COMMUNICATION_REPOSITORY, type CommunicationProvider, type CommunicationSubscription, type CommunicationType, type EscalationPolicy, type IncidentCommunication, type IncidentCommunicationRepository, type IncidentLifecycleEvent, type NotificationAudience, type PolicySelector, POLICY_SELECTOR, RecipientResolver } from '@faultline/notifications';
import { IncidentMessageBuilder } from './message-builder';
@Injectable()
export class LifecycleCommunicationService {
  constructor(@Inject(POLICY_SELECTOR)private readonly selector:PolicySelector,private readonly resolver:RecipientResolver,@Inject(INCIDENT_COMMUNICATION_REPOSITORY)private readonly history:IncidentCommunicationRepository,@Inject(COMMUNICATION_PROVIDER)private readonly provider:CommunicationProvider,private readonly messages:IncidentMessageBuilder){}
  async handle(event:IncidentLifecycleEvent,organizationId:string):Promise<void>{const policy=await this.selector.select(event.incident,organizationId);if(!policy)return;const type=this.type(event),subscription=this.subscription(type),service=event.incident.logicalService;for(const rule of policy.communicationRules??[]){if(!rule.subscriptions.includes(subscription)||rule.services?.length&&(!service||!rule.services.includes(service)))continue;const resolved=await this.resolver.resolve({id:`communication:${rule.audience}`,order:1,target:rule.target,channels:rule.channels,maximumAttempts:1,retryDelayMs:0,waitBeforeNextStepMs:0});for(const item of resolved.recipients){if(item.recipient.audience!==rule.audience)continue;for(const channel of item.channels)await this.send(event,policy.id,rule.audience,item.recipient,channel,type,rule.minimumIntervalMs??0);}}}
  private async send(event:IncidentLifecycleEvent,policyId:string,audience:NotificationAudience,recipient:{id:string;name:string;phoneNumber:string;audience:NotificationAudience},channel:'VOICE'|'SMS',type:CommunicationType,minInterval:number){const version=this.version(event),key=`${event.incident.id}:${audience}:${recipient.id}:${channel}:${type}:${version}`;if(await this.history.findByDedupeKey(key))return;if(minInterval>0){const recent=(await this.history.listForIncident(event.incident.id)).filter((value)=>value.audience===audience&&value.recipientId===recipient.id&&value.channel===channel&&value.communicationType===type&&value.status==='SENT').at(-1);if(recent&&Date.parse(event.occurredAt)-Date.parse(recent.sentAt??recent.createdAt)<minInterval)return;}const now=new Date().toISOString();let communication:IncidentCommunication={id:randomUUID(),incidentId:event.incident.id,audience,recipientId:recipient.id,channel,communicationType:type,messageVersion:version,status:'PENDING',createdAt:now,dedupeKey:key};await this.history.save(communication);try{const message=this.messages.buildLifecycle(event,audience);const metadata={incidentId:event.incident.id,communicationId:communication.id,policyId};const result=channel==='VOICE'?await this.provider.startVoiceCall({recipient,message,metadata,context:{incident_id:event.incident.id,lifecycle_state:event.state,severity:event.incident.severity,affected_service:event.incident.logicalService??event.incident.primaryResource.workload??''}}):await this.provider.sendSms({recipient,message,metadata});communication={...communication,status:'SENT',sentAt:now,providerRequestId:result.requestId};}catch{communication={...communication,status:'FAILED'};}await this.history.save(communication);}
  private type(event:IncidentLifecycleEvent):CommunicationType{return event.type==='INCIDENT_CREATED'?'INITIAL':event.type==='INCIDENT_RESOLVED'?'RESOLUTION':event.type==='INCIDENT_ETA_UPDATED'?'ETA_UPDATE':'STATUS_UPDATE';}
  private subscription(type:CommunicationType):CommunicationSubscription{return type==='INITIAL'?'INITIAL':type==='RESOLUTION'?'RESOLUTION':'STATUS_UPDATES';}
  private version(event:IncidentLifecycleEvent){return createHash('sha256').update(JSON.stringify([event.state,event.incident.severity,event.incident.estimatedRestorationAt??'',event.incident.serviceImpact??''])).digest('hex').slice(0,16);}
}
