import { randomUUID } from 'node:crypto';
import { Inject, Injectable, OnModuleDestroy, OnModuleInit } from '@nestjs/common';
import { INCIDENT_REPOSITORY,type IncidentRepository } from '@faultline/incidents';
import { COMMUNICATION_PROVIDER,ESCALATION_EXECUTION_REPOSITORY,ESCALATION_POLICY_REPOSITORY,NOTIFICATION_ATTEMPTS,NOTIFICATION_AUDIT_REPOSITORY,type CommunicationProvider,type EscalationExecutionRepository,type EscalationPolicyRepository,type NotificationAttemptRepository,type NotificationAuditRepository } from '@faultline/notifications';
import { HealthService } from '@faultline/platform';
import { NOTIFICATION_CONFIG,type NotificationWorkerConfig } from './config';
import { NotificationService } from './notification.service';
@Injectable()
export class RecoverySchedulerService implements OnModuleInit,OnModuleDestroy {
  readonly name='notification-scheduler';private readonly workerId=randomUUID();private timer?:NodeJS.Timeout;private running=false;private lastSuccessfulRun=0;
  constructor(@Inject(NOTIFICATION_CONFIG)private readonly config:NotificationWorkerConfig,@Inject(ESCALATION_EXECUTION_REPOSITORY)private readonly executions:EscalationExecutionRepository,@Inject(ESCALATION_POLICY_REPOSITORY)private readonly policies:EscalationPolicyRepository,@Inject(INCIDENT_REPOSITORY)private readonly incidents:IncidentRepository,@Inject(NOTIFICATION_ATTEMPTS)private readonly attempts:NotificationAttemptRepository,@Inject(NOTIFICATION_AUDIT_REPOSITORY)private readonly audit:NotificationAuditRepository,@Inject(COMMUNICATION_PROVIDER)private readonly provider:CommunicationProvider,private readonly notifications:NotificationService,health:HealthService){health.register(this,{critical:false});}
  async onModuleInit(){await this.tick();this.timer=setInterval(()=>void this.tick(),this.config.schedulerPollMs);this.timer.unref();}
  onModuleDestroy(){if(this.timer)clearInterval(this.timer);}
  async ping(){if(!this.lastSuccessfulRun||Date.now()-this.lastSuccessfulRun>this.config.schedulerPollMs*3)throw new Error('Notification scheduler is stalled');}
  async tick(){if(this.running)return;this.running=true;try{const now=new Date(),nowIso=now.toISOString(),leaseUntil=new Date(now.getTime()+this.config.schedulerLeaseMs).toISOString();for(const candidate of await this.executions.listDue(nowIso)){const claimed=await this.executions.claimDue(candidate.incidentId,this.workerId,nowIso,leaseUntil);if(!claimed)continue;const incident=await this.incidents.getIncident(claimed.incidentId),policy=await this.policies.get(claimed.policyId);if(!incident||!policy){await this.executions.save({...claimed,status:'CANCELLED',nextAttemptAt:undefined,completedAt:nowIso,updatedAt:nowIso});continue;}await this.notifications.recover(claimed,incident,policy);}const staleBefore=new Date(now.getTime()-this.config.staleAttemptMs).toISOString();for(const attempt of await this.attempts.listRecoverable(staleBefore)){if(!attempt.providerRequestId)continue;try{const status=await this.provider.getCallStatus(attempt.providerRequestId);await this.notifications.processProviderEvent(status);}catch{/* Retell outage leaves the attempt recoverable for the next poll. */}}const day=86_400_000;await this.attempts.purgeCompleted(new Date(now.getTime()-this.config.attemptRetentionDays*day).toISOString());await this.audit.purge(new Date(now.getTime()-this.config.auditRetentionDays*day).toISOString());this.lastSuccessfulRun=Date.now();}catch{/* Database/provider recovery failures are retried on the next poll and exposed by health. */}finally{this.running=false;}}
}
