import type { QueryResultRow } from 'pg';
import type {
  Contact, ContactRepository, EscalationExecution, EscalationExecutionRepository, EscalationPolicy,
  EscalationPolicyRepository, IncidentAcknowledgement, IncidentAcknowledgementRepository, NotificationAttempt,
  NotificationAttemptRepository, NotificationAuditEvent, NotificationAuditRepository, NotificationGroup,
  NotificationGroupRepository, IncidentCommunication, IncidentCommunicationRepository,
  IdempotencyStore, NotificationStatus,
  AcknowledgementTransaction,
  OnCallSchedule,OnCallScheduleRepository,OnCallShift,OnCallShiftRepository,AvailabilityOverride,AvailabilityOverrideRepository,
} from '@faultline/notifications';
import { canTransitionNotificationStatus, sanitizeProviderMetadata } from '@faultline/notifications';
import type { PostgresConnection } from './index';

interface AggregateRow<T> extends QueryResultRow { aggregate: T; }
abstract class AggregateRepository<T extends { id: string; organizationId: string }> {
  constructor(protected readonly db: PostgresConnection, private readonly table: string) {}
  async create(value: T): Promise<T> { await this.db.pool.query(`INSERT INTO ${this.table} (id, organization_id, aggregate) VALUES ($1,$2,$3)`, [value.id, value.organizationId, JSON.stringify(value)]); return structuredClone(value); }
  async update(value: T): Promise<T> { const result = await this.db.pool.query(`UPDATE ${this.table} SET organization_id=$2, aggregate=$3, updated_at=now() WHERE id=$1`, [value.id, value.organizationId, JSON.stringify(value)]); if (!result.rowCount) throw new Error('Entity not found'); return structuredClone(value); }
  async get(id: string): Promise<T | undefined> { const result = await this.db.pool.query<AggregateRow<T>>(`SELECT aggregate FROM ${this.table} WHERE id=$1`, [id]); return result.rows[0]?.aggregate ? structuredClone(result.rows[0].aggregate) : undefined; }
  async list(organizationId?: string): Promise<readonly T[]> { const result = await this.db.pool.query<AggregateRow<T>>(`SELECT aggregate FROM ${this.table}${organizationId ? ' WHERE organization_id=$1' : ''} ORDER BY updated_at DESC`, organizationId ? [organizationId] : []); return result.rows.map((row) => structuredClone(row.aggregate)); }
}
export class PostgresContactRepository extends AggregateRepository<Contact> implements ContactRepository { constructor(db: PostgresConnection) { super(db, 'notification_contacts'); } }
export class PostgresNotificationGroupRepository extends AggregateRepository<NotificationGroup> implements NotificationGroupRepository { constructor(db: PostgresConnection) { super(db, 'notification_groups'); } }
export class PostgresEscalationPolicyRepository extends AggregateRepository<EscalationPolicy> implements EscalationPolicyRepository { constructor(db: PostgresConnection) { super(db, 'escalation_policies'); } }
export class PostgresOnCallScheduleRepository extends AggregateRepository<OnCallSchedule> implements OnCallScheduleRepository {constructor(db:PostgresConnection){super(db,'on_call_schedules');}override async create(value:OnCallSchedule){await this.db.pool.query('INSERT INTO on_call_schedules (id,organization_id,team_id,aggregate) VALUES ($1,$2,$3,$4)',[value.id,value.organizationId,value.teamId,JSON.stringify(value)]);return structuredClone(value);}override async update(value:OnCallSchedule){const result=await this.db.pool.query('UPDATE on_call_schedules SET organization_id=$2,team_id=$3,aggregate=$4,updated_at=now() WHERE id=$1',[value.id,value.organizationId,value.teamId,JSON.stringify(value)]);if(!result.rowCount)throw new Error('Entity not found');return structuredClone(value);}}
abstract class PostgresScheduleChildRepository<T extends {id:string;scheduleId:string;startsAt:string;endsAt:string}>{constructor(protected readonly db:PostgresConnection,private readonly table:string){}async create(value:T){await this.db.pool.query(`INSERT INTO ${this.table} (id,schedule_id,starts_at,ends_at,aggregate) VALUES ($1,$2,$3,$4,$5)`,[value.id,value.scheduleId,value.startsAt,value.endsAt,JSON.stringify(value)]);return structuredClone(value);}async get(id:string){const result=await this.db.pool.query<AggregateRow<T>>(`SELECT aggregate FROM ${this.table} WHERE id=$1`,[id]);return result.rows[0]?.aggregate?structuredClone(result.rows[0].aggregate):undefined;}async listForSchedule(id:string){const result=await this.db.pool.query<AggregateRow<T>>(`SELECT aggregate FROM ${this.table} WHERE schedule_id=$1 ORDER BY starts_at`,[id]);return result.rows.map(r=>structuredClone(r.aggregate));}async findActive(id:string,at:string){const result=await this.db.pool.query<AggregateRow<T>>(`SELECT aggregate FROM ${this.table} WHERE schedule_id=$1 AND starts_at <= $2 AND ends_at > $2 ORDER BY starts_at DESC LIMIT 1`,[id,at]);return result.rows[0]?.aggregate?structuredClone(result.rows[0].aggregate):undefined;}async hasOverlap(id:string,start:string,end:string,excludeId?:string){const result=await this.db.pool.query(`SELECT 1 FROM ${this.table} WHERE schedule_id=$1 AND starts_at < $3 AND $2 < ends_at AND ($4::text IS NULL OR id<>$4) LIMIT 1`,[id,start,end,excludeId??null]);return!!result.rowCount;}}
export class PostgresOnCallShiftRepository extends PostgresScheduleChildRepository<OnCallShift> implements OnCallShiftRepository {constructor(db:PostgresConnection){super(db,'on_call_shifts');}}
export class PostgresAvailabilityOverrideRepository extends PostgresScheduleChildRepository<AvailabilityOverride> implements AvailabilityOverrideRepository {constructor(db:PostgresConnection){super(db,'availability_overrides');}}

export class PostgresNotificationAttemptRepository implements NotificationAttemptRepository {
  constructor(private readonly db: PostgresConnection) {}
  async save(value: NotificationAttempt) { await this.db.pool.query(`INSERT INTO notification_attempts (id,incident_id,provider_request_id,aggregate) VALUES ($1,$2,$3,$4) ON CONFLICT (id) DO UPDATE SET provider_request_id=EXCLUDED.provider_request_id, aggregate=EXCLUDED.aggregate, updated_at=now()`, [value.id,value.incidentId,value.providerRequestId ?? null,JSON.stringify(value)]); return structuredClone(value); }
  async get(id: string) { return this.one('id', id); }
  async findByProviderRequestId(id: string) { return this.one('provider_request_id', id); }
  async listForIncident(id: string) { const result = await this.db.pool.query<AggregateRow<NotificationAttempt>>('SELECT aggregate FROM notification_attempts WHERE incident_id=$1 ORDER BY updated_at', [id]); return result.rows.map((row) => structuredClone(row.aggregate)); }
  async updateStatus(id:string,status:NotificationStatus,completedAt?:string,metadata?:Readonly<Record<string,unknown>>){return this.updateStatusLocked(id,status,completedAt,metadata);}
  private async updateStatusLocked(id:string,status:NotificationStatus,completedAt?:string,metadata?:Readonly<Record<string,unknown>>){const client=await this.db.pool.connect();try{await client.query('BEGIN');const result=await client.query<AggregateRow<NotificationAttempt>>('SELECT aggregate FROM notification_attempts WHERE id=$1 FOR UPDATE',[id]);const current=result.rows[0]?.aggregate;if(!current)throw new Error('Notification attempt not found');if(current.status===status||!canTransitionNotificationStatus(current.status,status)){await client.query('COMMIT');return{attempt:structuredClone(current),changed:false};}const attempt={...current,status,...(completedAt?{completedAt}:{}),...(metadata?{metadata:sanitizeProviderMetadata(metadata)}:{})};await client.query('UPDATE notification_attempts SET aggregate=$2,updated_at=now() WHERE id=$1',[id,JSON.stringify(attempt)]);await client.query('COMMIT');return{attempt:structuredClone(attempt),changed:true};}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}}
  async listRecoverable(staleBefore:string){const result=await this.db.pool.query<AggregateRow<NotificationAttempt>>(`SELECT aggregate FROM notification_attempts WHERE aggregate->>'status'='PENDING' OR (aggregate->>'status'='IN_PROGRESS' AND (aggregate->>'startedAt')::timestamptz < $1)`,[staleBefore]);return result.rows.map(r=>structuredClone(r.aggregate));}
  async purgeCompleted(before:string){const result=await this.db.pool.query('DELETE FROM notification_attempts WHERE (aggregate->>\'completedAt\')::timestamptz < $1',[before]);return result.rowCount??0;}
  private async one(column: 'id'|'provider_request_id', value: string) { const result = await this.db.pool.query<AggregateRow<NotificationAttempt>>(`SELECT aggregate FROM notification_attempts WHERE ${column}=$1`, [value]); return result.rows[0]?.aggregate ? structuredClone(result.rows[0].aggregate) : undefined; }
}
export class PostgresIncidentCommunicationRepository implements IncidentCommunicationRepository {
  constructor(private readonly db:PostgresConnection){}
  async save(value:IncidentCommunication){await this.db.pool.query(`INSERT INTO incident_communications (id,incident_id,dedupe_key,aggregate,created_at) VALUES ($1,$2,$3,$4,$5) ON CONFLICT (id) DO UPDATE SET aggregate=EXCLUDED.aggregate`,[value.id,value.incidentId,value.dedupeKey,JSON.stringify(value),value.createdAt]);return structuredClone(value);}
  async findByDedupeKey(key:string){const result=await this.db.pool.query<AggregateRow<IncidentCommunication>>('SELECT aggregate FROM incident_communications WHERE dedupe_key=$1',[key]);return result.rows[0]?.aggregate?structuredClone(result.rows[0].aggregate):undefined;}
  async listForIncident(id:string){const result=await this.db.pool.query<AggregateRow<IncidentCommunication>>('SELECT aggregate FROM incident_communications WHERE incident_id=$1 ORDER BY created_at',[id]);return result.rows.map((row)=>structuredClone(row.aggregate));}
}
export class PostgresEscalationExecutionRepository implements EscalationExecutionRepository {
  constructor(private readonly db: PostgresConnection) {}
  async save(value: EscalationExecution) { await this.db.pool.query(`INSERT INTO escalation_executions (incident_id,policy_id,status,next_attempt_at,lease_owner,lease_expires_at,aggregate) VALUES ($1,$2,$3,$4,$5,$6,$7) ON CONFLICT (incident_id) DO UPDATE SET policy_id=EXCLUDED.policy_id,status=EXCLUDED.status,next_attempt_at=EXCLUDED.next_attempt_at,lease_owner=EXCLUDED.lease_owner,lease_expires_at=EXCLUDED.lease_expires_at,aggregate=EXCLUDED.aggregate,updated_at=now()`, [value.incidentId,value.policyId,value.status,value.nextAttemptAt??null,value.leaseOwner??null,value.leaseExpiresAt??null,JSON.stringify(value)]); return structuredClone(value); }
  async get(id: string) { const result = await this.db.pool.query<AggregateRow<EscalationExecution>>('SELECT aggregate FROM escalation_executions WHERE incident_id=$1',[id]); return result.rows[0]?.aggregate ? structuredClone(result.rows[0].aggregate) : undefined; }
  async listDue(now:string){const result=await this.db.pool.query<AggregateRow<EscalationExecution>>(`SELECT aggregate FROM escalation_executions WHERE status='ACTIVE' AND next_attempt_at <= $1 AND (lease_expires_at IS NULL OR lease_expires_at <= $1) ORDER BY next_attempt_at LIMIT 100`,[now]);return result.rows.map(r=>structuredClone(r.aggregate));}
  async claimDue(id:string,owner:string,now:string,until:string){const result=await this.db.pool.query<AggregateRow<EscalationExecution>>(`UPDATE escalation_executions SET lease_owner=$2,lease_expires_at=$4,aggregate=jsonb_set(jsonb_set(aggregate,'{leaseOwner}',to_jsonb($2::text)),'{leaseExpiresAt}',to_jsonb($4::text)),updated_at=now() WHERE incident_id=$1 AND status='ACTIVE' AND next_attempt_at <= $3 AND (lease_expires_at IS NULL OR lease_expires_at <= $3) RETURNING aggregate`,[id,owner,now,until]);return result.rows[0]?.aggregate?structuredClone(result.rows[0].aggregate):undefined;}
}
export class PostgresIncidentAcknowledgementRepository implements IncidentAcknowledgementRepository {
  constructor(private readonly db: PostgresConnection) {}
  async save(value: IncidentAcknowledgement) { await this.db.pool.query(`INSERT INTO incident_acknowledgements (incident_id,aggregate) VALUES ($1,$2) ON CONFLICT (incident_id) DO UPDATE SET aggregate=EXCLUDED.aggregate`,[value.incidentId,JSON.stringify(value)]); return structuredClone(value); }
  async get(id: string) { const result = await this.db.pool.query<AggregateRow<IncidentAcknowledgement>>('SELECT aggregate FROM incident_acknowledgements WHERE incident_id=$1',[id]); return result.rows[0]?.aggregate ? structuredClone(result.rows[0].aggregate) : undefined; }
}
export class PostgresNotificationAuditRepository implements NotificationAuditRepository {
  constructor(private readonly db: PostgresConnection) {}
  async append(value: NotificationAuditEvent) { await this.db.pool.query('INSERT INTO notification_audit_events (id,incident_id,occurred_at,aggregate) VALUES ($1,$2,$3,$4) ON CONFLICT (id) DO NOTHING',[value.id,value.incidentId,value.timestamp,JSON.stringify(value)]); }
  async list(id: string) { const result = await this.db.pool.query<AggregateRow<NotificationAuditEvent>>('SELECT aggregate FROM notification_audit_events WHERE incident_id=$1 ORDER BY occurred_at',[id]); return result.rows.map((row) => structuredClone(row.aggregate)); }
  async purge(before:string){const result=await this.db.pool.query('DELETE FROM notification_audit_events WHERE occurred_at < $1',[before]);return result.rowCount??0;}
}
export class PostgresIdempotencyStore implements IdempotencyStore {constructor(private readonly db:PostgresConnection){}async claim(key:string){const result=await this.db.pool.query('INSERT INTO notification_idempotency (key) VALUES ($1) ON CONFLICT DO NOTHING RETURNING key',[key]);return!!result.rowCount;}async release(key:string){await this.db.pool.query('DELETE FROM notification_idempotency WHERE key=$1',[key]);}}
export class PostgresAcknowledgementTransaction implements AcknowledgementTransaction {constructor(private readonly db:PostgresConnection){}async acknowledge(input:Parameters<AcknowledgementTransaction['acknowledge']>[0]){const client=await this.db.pool.connect();try{await client.query('BEGIN');await client.query(`INSERT INTO incident_acknowledgements (incident_id,aggregate) VALUES ($1,$2) ON CONFLICT (incident_id) DO NOTHING`,[input.acknowledgement.incidentId,JSON.stringify(input.acknowledgement)]);await client.query(`UPDATE escalation_executions SET status='ACKNOWLEDGED',next_attempt_at=NULL,lease_owner=NULL,lease_expires_at=NULL,aggregate=$2,updated_at=now() WHERE incident_id=$1 AND status='ACTIVE'`,[input.execution.incidentId,JSON.stringify(input.execution)]);if(input.attempt)await client.query('UPDATE notification_attempts SET aggregate=$2,updated_at=now() WHERE id=$1',[input.attempt.id,JSON.stringify(input.attempt)]);for(const event of input.events)await client.query('INSERT INTO notification_audit_events (id,incident_id,occurred_at,aggregate) VALUES ($1,$2,$3,$4) ON CONFLICT DO NOTHING',[event.id,event.incidentId,event.timestamp,JSON.stringify(event)]);await client.query('COMMIT');}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}}}
