apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: faultline-system
resources:
  - namespace.yaml
  - rbac.yaml
  - logs.yaml
  - events.yaml
configMapGenerator:
  - name: faultline-collector-logs-config
    files:
      - config.yaml=collector-logs.yaml
  - name: faultline-collector-events-config
    files:
      - config.yaml=collector-events.yaml
